import { RAW_CONFIG_LIST_CBSL } from "./RAW_CONFIG_LIST_CBSL";
import { RAW_CONFIG_LIST_WORLD_BANK } from "./RAW_CONFIG_LIST_WORLD_BANK";

export const RAW_CONFIG_LIST = [].concat(
  RAW_CONFIG_LIST_CBSL,
  RAW_CONFIG_LIST_WORLD_BANK
);
