import json
from utils import WWW, File, Log, hashx
log = Log('generate_raw_config_list.py')

URL = 'https://raw.githubusercontent.com'+'/nuuuwan/cbsl/data/edl_summary.json'
URL_WORLDBANK = 'https://raw.githubusercontent.com'+'/nuuuwan/cbsl/data/other_sources/world_bank/summary.json'

def main_cbsl():
    data = WWW(URL).readJSON()
    n_data = len(data)
    h = hashx.md5(json.dumps(data, sort_keys=True))
    content = f'''// Auto-generated by scripts_py/generate_raw_config_list.py
// n = {n_data}
// hash = {h};

export const RAW_CONFIG_LIST_CBSL = {json.dumps(data, indent=2)};

    '''

    file_path = 'src/nonview/core/RAW_CONFIG_LIST_CBSL.js'
    File(file_path).write(content)
    log.info(f'Wrote {n_data} configs to {file_path}')


def main_worldbank():
    data = WWW(URL_WORLDBANK).readJSON()
    n_data = len(data)
    h = hashx.md5(json.dumps(data, sort_keys=True))
    content = f'''// Auto-generated by scripts_py/generate_raw_config_list.py
// n = {n_data}
// hash = {h};

export const RAW_CONFIG_LIST_WORLD_BANK = {json.dumps(data, indent=2)};

    '''

    file_path = 'src/nonview/core/RAW_CONFIG_LIST_WORLD_BANK.js'
    File(file_path).write(content)
    log.info(f'Wrote {n_data} configs to {file_path}')


if __name__ == '__main__':
    main_cbsl()
    main_worldbank()