from utils import TimeFormat, Time, Log, File
log = Log('version')
def main():
    version = TimeFormat('v%Y%m%d.%H%M%S').stringify(Time.now())
    content = f'''// Auto generated by scripts_py/version.py
export const VERSION = "{version}";
'''

    file_path = 'src/nonview/core/VERSION.js'
    File(file_path).write(content)
    log.info(f'Wrote {version} to {file_path}')

if __name__ == '__main__':
    main()