import sys
import os
from utils import TimeFormat, Time, Log, File
log = Log('version')

VERSION_FILE_PATH = 'src/nonview/core/VERSION.js'
    

def main(version_info):
    version = TimeFormat('v%Y%m%d.%H%M').stringify(Time.now())
    content = f'''// Auto generated by scripts_py/version.py
export const VERSION = "{version}";
export const VERSION_INFO = "{version_info}";
'''

    File(VERSION_FILE_PATH).write(content)
    log.info(f'Wrote {version} to {VERSION_FILE_PATH}')

    os.system(f'git add {VERSION_FILE_PATH}')
    os.system(f'git commit -m "Update version {version}"')

if __name__ == '__main__':
    version_info = sys.argv[1]
    main(version_info)
